export const skillImages = {
    Appfarm: "appfarm-logo.png",
    Azure: "azure-logo.png",
    Bioformats: "bioformats-logo.png",
    BeautifulSoup: "bs4-logo.png",
    ChartJS: "chartjs-logo.png",
    "C#": "csharp-logo.png",
    Express: "express-logo.png",
    Flask: "flask-logo.png",
    GraphQL: "graphql-logo.png",
    Java: "java-logo.png",
    Javascript: "js-logo.png",
    LineAPI: "line-api-logo.png",
    MetaXR: "meta-logo.png",
    MongoDB: "mongodb-logo.png",
    MRTK3: "mrtk3-logo.png",
    MySQL: "mysql-logo.png",
    Node: "node-logo.png",
    Python: "py-logo.png",
    React: "react-logo.png",
    Selenium: "selenium-logo.png",
    Unity: "unity-logo.png",
    WebRTC: "webrtc-logo.png",
    Websocket: "websocket-logo.png",
}
