export const skillImages = {
    BeautifulSoup: "bs4-logo.png",
    CSS: "css-logo.png",
    Express: "express-logo.png",
    Flask: "flask-logo.png",
    Gurobi: "gurobi-logo.png",
    HTML: "html-logo.png",
    Java: "java-logo.png",
    Javascript: "js-logo.png",
    MongoDB: "mongodb-logo.png",
    MySQL: "mysql-logo.png",
    Node: "node-logo.png",
    Pandas: "pandas-logo.png",
    Python: "py-logo.png",
    React: "react-logo.png",
    Selenium: "selenium-logo.png",
    SQLAlchemy: "sqlalchemy-logo.png",
    Tkinter: "tkinter-logo.png",
}
